# Build stage
FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o route-planner-api .

# Run stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/route-planner-api .
EXPOSE 8080
CMD ["./route-planner-api"]